baseurl         = "https://andreadpro.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Example Blog Site"
  subtitle    = "My Blog"

  cover       = "uploads/sunflower.jpg"
  description = "My awesome blog site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "andrea.desiderio.522"
  githubName = "andreadesiderio"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Andrea Desiderio"
  authorAvatar = "uploads/bee.jpg"
  authorLocation = "Onalaska, Wa"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Coder, Developer."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/projects/"
  weight = 100

[[menu.main]]
  name = "Resources"
  url = "/categories/resources/"
  weight = 99

[[menu.main]]
  name = "Portfolio"
  url = "https://google.com/"
  weight = 95